name: send tg notification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  send:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: send
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        run: python tg-notification.py
